[package]
name = "yirgacheffe"
version = "0.1.0"
authors = ["JasonWang <1103870790@qq.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["handlebars_templates", "tera_templates"]
